apiVersion: v1
kind: Secret
metadata:
  name: rancher-app-secret
  namespace: rancher-app
type: Opaque
stringData:
  API_KEY: "Some-Strong-Api-Key-You-Know-?"
  METRICS_TOKEN: "Some-Long-Random-Metrics-Token"