apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher-app
  namespace: rancher-app
  labels:
    app: rancher-app
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: rancher-app
  endpoints:
    - port: http
      path: /api/metrics
      interval: 30s
      scrapeTimeout: 10s